#!/usr/bin/env php
<?php

use App\Config;
use Darken\Console\Application;

require __DIR__ . '/vendor/autoload.php';

$config = new Config(
    rootDirectoryPath: getcwd(),
);

$exitCode = (new Application($config))
    ->run();

exit($exitCode);